### ISSUE TITLE
SS causes segfault and crashes JVM

### ISSUE THREAD

**Issue by jk-5** [md-5/SpecialSource#15]
When running forgegradle's build task, FG tries to reobfuscate the produced jars using SS. Somehow, this crashes the JVM.
Gradle log (not much information): http://pastebin.com/enktViLV
JVM error report: http://pastebin.com/iWNdMrAQ
This is not an FG issue, as the lines in the JVM error report clearly point to specialsource.

**Comment by AbrarSyed** [comment]
was an FG issue. been fixed.
