### ISSUE TITLE
How to use SpecialSource with Cauldron?

### ISSUE THREAD

**Issue by NDruce** [md-5/SpecialSource#27]
I read this tutorial and ported my plugin on Cauldron 1.7.10:
http://bukkit.org/threads/tutorial-advanced-how-to-develop-plugins-using-mcp-for-nms-via-asm-remapping.131060/

But my plugin doesn't work. I decompiled reobfuscated version and some classes/fields was reobfuscated, but not all. Then I run script for remap to CB and plugin deobfuscating instead of reobfuscate fully. bloodmc ported Citizens2 the same way, but I can't write him, he not reply.
My CB remap script: `java -jar SpecialSource.jar --in-jar OnlyFlags-obf.jar --out-jar OnlyFlags_Cauldron.jar --srg-in obf2pkgmcp.srg --out-shade-relocation net.minecraft.server=net.minecraft.server.v1_7_R4,org.bouncycastle=net.minecraft.v1_7_R4.org.bouncycastle`

**Comment by md-5** [comment]
Can you please talk about what doesn't work......

**Comment by iBars** [comment]
There is error in console: http://pastebin.com/BadEfXEv
Error on this line: http://i.imgur.com/XY82RUI.png
Used scripts (with SS and non-obf plugin): https://www.dropbox.com/s/k6f2dkbvz6aksxa/scripts.rar?dl=0

**Comment by iBars** [comment]
I understand the error! SpecialSource not remapped function setPosition to b. But mappings contains
`MD: sa/b (DDD)V net/minecraft/entity/Entity/setPosition (DDD)V`
Whats wrong? Thanks

**Comment by iBars** [comment]
Fixed. Just by cast EntityWitherSkull to Entity
