### ISSUE TITLE
Inner classes are not actually renamed

### ISSUE THREAD

**Issue by killjoy1221** [md-5/SpecialSource#30]
It updates the file name and references, but the original class name is still in the bytecode, which is what decompilers are using to name the class. This has become an issue with Minecraft 1.8.3 since inner classes and other attributes were kept.

This is what is in the relevant bytecode in both the owner's class and the class in question, the first name after `INNERCLASS` being the file name, second is the owner, third is the actual class name. `Test.Original` was renamed to `Test.Renamed`.
```java
  // access flags 0x4019
  public final static enum INNERCLASS Test$Renamed Test Original
```

Using an example from Minecraft 1.8.3:
```java
  // access flags 0x4019
  public final static enum INNERCLASS net/minecraft/util/Util$OS net/minecraft/util/Util a
```
For the Util class, I used these srg lines.
```
CL: h$a net/minecraft/util/Util$OS
CL: h net/minecraft/util/Util
```

**Comment by md-5** [comment]
Update, this was fixed

**Comment by AbrarSyed** [comment]
https://github.com/md-5/SpecialSource/commit/e24ed53012b46673e0851c0f0e69ce7ac50d895f
