### ISSUE TITLE
SS crashes due to classes not in the mapping. Should skip instead.

### ISSUE THREAD

**Issue by Stenlan** [md-5/SpecialSource#34]
There are some classes that are not included in a jar I want to "deobfuscate" the names of. These classes were created by myself and already have the right names, so instead of trying to rename them, SpecialSource should skip them and only rename the ones that are included in the obfuscation map.

Crash: (expected)
http://pastebin.com/raw.php?i=Jf0xZpWf

If this feature could get added, that'd be awesome.

**Comment by md-5** [comment]
Nope, that looks like you have a corrupted class file in your jar.

**Comment by Stenlan** [comment]
Well I think that is not the case because I can run it just fine.
Op 21 sep. 2015 09:04 schreef "md-5" <notifications@github.com>:

**Comment by md-5** [comment]
If you made your jar on OS X you could have a .DS_STORE or some other class file which isn't used.
Maybe you want to attach it?

**Comment by Stenlan** [comment]
If I can fix it without attaching it, I'd rather do that, but otherwise
I'll attach it. I removed the DS store and it gives another error now. Ill
send it in a minute
Op 21 sep. 2015 09:25 schreef "md-5" <notifications@github.com>:

**Comment by Stenlan** [comment]
Ok here's the file: https://d.maxfile.ro/ogmbkaguwc.jar 

It works like it has renamed them, but after looking in the class file, nothing has been renamed. There's no error though.
