### ISSUE TITLE
SS doesn't remap methods implemented in a lambda

### ISSUE THREAD

**Issue by matthewprenger** [md-5/SpecialSource#36]
This problem has come up as more and more mods are moving to Java 8. SpecialSource appears to not fully remap the method names of interfaces and abstract classes when they are implemented using a lambda. 

Test class:
```java
public class Test {
    public static void main(String[] args) {
        Foo f = () -> "Matthew";

        System.out.println(f.getName());
    }

    private interface Foo {
        String getName();
    }
}
```

SRG line:
```
MD: Test$Foo/getName ()Ljava/lang/String; Test$Foo/getFoo ()Ljava/lang/String;
```

Error:
```
Exception in thread "main" java.lang.AbstractMethodError: Test$$Lambda$1/791452441.getFoo()Ljava/lang/String;
	at Test.main(Test.java:5)
```

Source: MinecraftForge/ForgeGradle#336

**Comment by md-5** [comment]
This is verging on impossible to solve without reimplementing half of Java within SS as far as I can tell.
You're welcome to look at the bytecode and offer suggestions

**Comment by matthewprenger** [comment]
@md-5 Figured it out. The key is overriding `mapInvokeDynamicMethodName` in the ASM Remapper class. This remapper correctly remaps the above test code:
```java
final Remapper remapper = new Remapper() {
    @Override
    public String mapMethodName(String owner, String name, String desc) {
        if ("getName".equals(name)) {
            return "getFoo";
        }
        return name;
    }

    @Override
    public String mapInvokeDynamicMethodName(String name, String desc) {
        if ("getName".equals(name)) {
            return "getFoo";
        }
        return super.mapInvokeDynamicMethodName(name, desc);
    }
};
```
Note: the `desc` parameter of `mapInvokeDynamicMethodName` in this case is: `()LTest$Foo;`

**Comment by md-5** [comment]
You still need to evaluate `desc` to determine the owner which you have not done. I'd also bet there are plenty of other valid invokedynamic constructions that are declared differently.

**Comment by matthewprenger** [comment]
Yeah I didn't bother evaluating `desc` for this simple example, but I understand that it's needed.

**Comment by LexManos** [comment]
Potential solution for this, it has not been excessivly tested as there is no test framework for SS that I can find.
https://github.com/LexManos/SpecialSource/commit/ef5ac81fdd55e18a6357ed45c1b6303906906c07

**Comment by matthewprenger** [comment]
This does seem to fix the above test code.
