### ISSUE TITLE
Special Source Source Level 7 Suport

### ISSUE THREAD

**Issue by sameer** [md-5/SpecialSource#38]
Special Source is unable to support source level 7, producing errors after building projects at runtime like [these](http://hastebin.com/otemobivet.coffee). 
While `-noverify` is a temporary fix, the full reason as to why it is happening is explained on StackOverflow [here](https://stackoverflow.com/questions/12774672/java-7-inconsistent-stackmap-frames-need-help-understanding-why-solution-wor#12925602). 

I believe Special Source is at fault, but I am not sure. If it is, is it possible to implement what is mentioned in the StackOverflow post?

**Comment by md-5** [comment]
It definitely has some support, because we do 1.8 lambdas etc fine. It's possible you are calling SS without a complete classpath so ASM cannot complete the stackmap frame. Alternatively it is an ASM bug.

**Comment by Robotia** [comment]
Then again, it could be ForgeGradle's reobf. I'm not sure what the issue is :/

**Comment by Robotia** [comment]
I might be using an old version of SS actually...
