### ISSUE TITLE
SpecialSource doesn't remap fields properly

### ISSUE THREAD

**Issue by PizzaCrust** [md-5/SpecialSource#39]
Mapped Code:
```java
public class Test {
     private Test test = new Test();
}
```

Reversed Mapped Code:
```java
public class RemappedTest {
  private RemappedTest test = new RemappedTest();
}
```

It should be:
```java
public class RemappedTest {
  private RemappedTest a = new RemappedTest();
}
```

This is what is happening to me right now.

**Comment by md-5** [comment]
Your input is wrong, this trivial example definitely works, otherwise *everything* would be broken.

**Comment by PizzaCrust** [comment]
I have fixed this issue by add ```--live``` to "Enable runtime inheritance lookup".
