### ISSUE TITLE
Filedates bugged in jars produced by gradle

### ISSUE THREAD

**Issue by Sedridor** [md-5/SpecialSource#40]
All the jar files created by gradle build have their contained files and folders set to filedate 1980-01-01 0:00 modified and the created/accessed timestamps are completely missing (set to null?).
This makes it difficult to check when certain mods were released, as the downloaded jar's timestamp is set to the time of download, not the time of creation.

After closer inspection I've found the cause of the bug.
In `net/md_5/specialsource/JarRemapper.java` at line 212 there is `entry.setTime(0);`,
this line needs to be removed to fix the issue.

**Comment by md-5** [comment]
It's not actual a bug, it's for reproducible builds.

**Comment by AbrarSyed** [comment]
I definitely dont think reproduceable builds is the domain of SpecialSource.. if needed, another tool or something can be written just to strip out the timestamps..
