### ISSUE TITLE
IOException: Class not found

### ISSUE THREAD

**Issue by Hdadaw** [md-5/SpecialSource#54]
This happens when I try to generate a map:
![image](https://user-images.githubusercontent.com/32250813/41474045-88c7a80a-70ed-11e8-8ca2-0493911eceb2.png)

**Comment by md-5** [comment]
Do a and b have a Main-class defined?
Are they other than names identical ?
Can you provide them?

**Comment by Hdadaw** [comment]
[classezz.zip](https://github.com/md-5/SpecialSource/files/2108101/classezz.zip)

**Comment by md-5** [comment]
You have not defined a Main-Class in either a or b
