### ISSUE TITLE
How to remap method param names?

### ISSUE THREAD

**Issue by ShaneBeee** [md-5/SpecialSource#93]
I recently just started using SpecialSource programatically in an app.
I have everything worked out to remap (and its insanely fast so I'm grateful for that)

Last issue I have gotten down to is param names are always var1, var2, etc.

I know that CB/Spigot have these remapped, so Im assuming there is a way, I just dont know how.

This is what I have thus far:
https://github.com/ShaneBeeStudios/McDeob/blob/aefd7f02813fee73aa813c2fe97c25c653edab24/src/main/java/com/shanebeestudios/mcdeob/Processor.java#L159-L176

Example of what a method remaps to currently:
`public void playSound(SoundEvent var1, float var2, float var3) {`

Any help would be appreciated.

**Comment by md-5** [comment]
SpecialSource doesn't support local variable mapping as far as I know. In CB/Spigot the decompiler is just configured to use the type name as the base rather than 'var'.

**Comment by ShaneBeee** [comment]
ohhhhhh, ok.
Well, that is a bummer but I've survived this long.
Thanks for letting me know!

**Comment by md-5** [comment]
> WAIT, while I have you here, are you referring to Fernflower?

Yes but custom https://hub.spigotmc.org/stash/projects/SPIGOT/repos/fernflower/commits/383c4aba04ad915110b5666aaaf8258d3d2c5c8c#src%2Forg%2Fjetbrains%2Fjava%2Fdecompiler%2Futil%2FVarHelper.java

**Comment by ShaneBeee** [comment]
ahh, ok cool. thank you
